### ISSUE TITLE
Add Burst version for UpdateTransformJobManager

### ISSUE THREAD

**Issue by laicasaane** [gilzoide/unity-update-manager#15]
Currently `UpdateTransformJobManager` schedules an `UpdateTransformJob` thus even if user declares `AJobBehaviour<RotateBurstedJob, BurstUpdateTransformJob<RotateBurstedJob>>`, `RotateBurstedJob` won't be bursted.

This image is the current schedule code:
![image](https://github.com/gilzoide/unity-update-manager/assets/1594982/00c839ac-7329-477e-bdab-7e220f419bf8)

After I change the code to
```cs
protected override JobHandle ScheduleJob(JobHandle dependsOn)
{
    var job = new  BurstUpdateTransformJob<TData>
    {
        Data = _jobData.Data,
    };
    return ReadOnlyTransformAccess
        ? job.ScheduleReadOnly(_jobData.Transforms, JobBatchSize, dependsOn)
        : job.Schedule(_jobData.Transforms, dependsOn);
}
```

The result:
![image](https://github.com/gilzoide/unity-update-manager/assets/1594982/bf9690c7-6446-47c7-b40d-ed0db6c2926f)

**Comment by gilzoide** [comment]
Oh, you're right, I totally forgot to take into account the new `BurstUpdateJob` and `BurstUpdateTransformJob` structs in `UpdateJobManager` and `UpdateTransformJobManager` implementations 😅
This will require a new generics parameter in the manager classes, but with an overload that defaults to non-Burstified jobs, the new version will maintain compatibility with current projects and we have a nice non-breaking package update.

Thank you very much for the report, I'll look into it throughout the weekend and keep you posted.
Cheers \o/

**Comment by gilzoide** [comment]
Ok, so I got (what I think is) a better idea: instead of adding yet another generic type parameter, which would trigger annoying changes to the generic interface types and break the `[DependsOn(...)]` attribute, we can check if the job data type has the `[BurstCompile]` attribute and instantiate/schedule Burst-enabled jobs instead of non-Burst ones =]

I hope Unity doesn't go back to warning about we trying to use jobs marked with `[BurstCompile]` without referencing the concrete struct types anywhere. Hopefully, it only does that when instantiating the job 🤞

**Comment by gilzoide** [comment]
So, I like this project and was eager to solve the issue, so I created the `bugfix/use-burst-compiled-jobs` branch with the fix, but requiring that you manually add `[BurstCompile]` to your job struct definition, which shouldn't be much of a problem.
As far as I've tested, the warning I mentioned before is only logged when instantiating the job, so it seems fine.

Please test and let me know if it works for you. I'll update documentation later.

<hr/>

I'm thinking that since Burst support makes sense being a job struct attribute, maybe we could move the necessity of writing the concrete types `BurstUpdateJob<...>` and `BurstUpdateTransformJob<...>` from the job updatable interfaces to a new attribute, something like:
```cs
[BurstCompileJob(typeof(BurstUpdateJob<MyJob>))]
public struct MyJob : IUpdateJob
{
    public void Execute() {}
}
```
This attribute can even inherit from `BurstCompileAttribute`, so people can use a single attribute in job definitions.

What do you think?

**Comment by laicasaane** [comment]
> As far as I've tested, the warning I mentioned before is only logged when instantiating the job, so it seems fine.

I didn't encounter this warning though. On Unity 2022.3.11, Burst 1.8.10, Collections 2.1.4.

> This attribute can even inherit from BurstCompileAttribute, so people can use a single attribute in job definitions.

I like the idea. I think this code `AJobBehaviour<RotateBurstedJob, BurstUpdateTransformJob<RotateBurstedJob>>` is too much a boilerplate.

---

Oh, I understand what you mean of the warning now. Removing this `BurstUpdateTransformJob<RotateBurstedJob>` from the Behaviour and Burst doesn't know the concrete job to compile.

**Comment by laicasaane** [comment]
It turns out this doesn't work the way I want:

```cs
[BurstCompileJob(typeof(BurstUpdateJob<MyJob>))]
public struct MyJob : IUpdateJob
{
    public void Execute() {}
}

public class MyJobBehaviour : AJobBehaviour<MyJob>
{
...
}
```

Burst can't find `BurstUpdateJob<MyJob>` to compile because attribute isn't a Burst entry.

But this works so I think we can go with this fix for the time being.

```cs
[BurstCompile]
public struct MyJob : IUpdateJob
{
    public void Execute() {}
}

public class MyJobBehaviour : AJobBehaviour<MyJob, BurstUpdateJob<MyJob>>
{
...
}
```

**Comment by gilzoide** [comment]
> It turns out this doesn't work the way I want:

About the `[BurstCompileJob(typeof(...))]` thing, I was just spitballing the idea, this has not been implemented yet 😅
I'm surprised your project compiled. (Or maybe it did not, since `BurstCompileJobAttribute` class does not exist?)

> But this works so I think we can go with this fix for the time being.

Nice, thanks for testing! I'll try out the `[BurstCompileJob(...)]` idea and add some documentation on the new requirement for Burstified jobs.

**Comment by laicasaane** [comment]
> Or maybe it did not, since BurstCompileJobAttribute class does not exist?

Well, I implemented it myself to test the idea.

**Comment by gilzoide** [comment]
Well, turns out using `typeof(BurstUpdateJob<...>)` is not enough for the compiler to generate the concrete type and Burst won't compile it with just that =(
We'll have to stick with passing `BurstUpdateJob<...>` as a generic type parameter to something, but it doesn't need to be the job updatables, I'm thinking about creating a new dummy generic interface just for that, for people to put in their job definitions, something like the following `IBurstJob<>`:
```cs
[BurstCompile]
public struct MyJob : IUpdateJob, IBurstJob<BurstUpdateJob<MyJob>>
{
    public void Execute() {}
}

public class MyJobBehaviour : AJobBehaviour<MyJob>
{
    // ...
}
```

I don't know if it makes much difference, but I guess moving this clutter to the job definition makes more sense than letting it exist in the job updatable interfaces.

Any ideas?

> Well, I implemented it myself to test the idea.

Oooh, ok, got it!

**Comment by laicasaane** [comment]
> Any ideas?

Instead of inventing another interface, could you reuse what's already defined? If that's not possible, then another dummy interface is ok for me.

Interface actually is more helpful in case of nested private job. We don't have to expose it for Burst to pick up.

**Comment by gilzoide** [comment]
The only interface used in jobs is `IUpdateJob` and `IUpdateTrasnformJob`.
There could be `IUpdateJob<>` and `IUpdateTransformJob<>`, or we could use new names like `IBurstUpdateJob<>` and `IBurstUpdateTransformJob<>`. Both ways would work fine, interface inheritance is our friend in this one: the previous interfaces will still exist and new ones inherit from them.
Having new interfaces for Burst jobs could also remove the need to specify `[BurstCompile]` in the job definition: if the struct type implements `IBurstUpdate*Job<>`, then we use Burst-enabled jobs and that's it.

> Interface actually is more helpful in case of nested private job. We don't have to expose it for Burst to pick up.

I don't get what you mean by that, could you explain better?

**Comment by laicasaane** [comment]
What I mean is nested types that are private. But it's just a silly thought of mine, don't mind that. 😅

**Comment by laicasaane** [comment]
Actually the best solution would be source generator where it writes additional interface implementation for us, saves us from boilerplates. But source generator is hard and I don't recommend it for now.

**Comment by gilzoide** [comment]
It is not about interfaces, but rather about specifying the concrete version of the generic job type anywhere in code, so that Burst can compile it, and having a way to mark jobs as Burst-enabled.

I'm not going the source generator way, it's too much trouble to be worth. The only boilerplate here is writing `BurstUpdate*Job<...>` once per job type, I think it's fine.

I created here the `IBurstUpdateJob<>` and `IBurstUpdateTransformJob<>` interfaces and was able to force the type parameter to be one of `BurstUpdateJob<...>` or `BurstUpdateTransformJob<...>` (well, with generics constraints the best I was able to do is force the parameter to implement `IInternalBurstJob`, which only the Burst jobs implement).
```cs
public struct MyJob : IBurstUpdateJob<BurstUpdateJob<MyJob>>
{
    public void Execute() {}
}
```

Given the limitation, I think it's the best option for now: a single type parameter as boilerplate, but specified in the job struct type instead of job updatables.
